# use container-based infrastructure
sudo: false
language: scala
scala: 2.11.7
jdk: oraclejdk8

addons:
  postgresql: "9.4"

before_script: ./scripts/pre-publish.sh
script:        ./scripts/ci-build.sh
after_success: ./scripts/publish.sh

env:
  global:
  - BUILD_NUMBER=$TRAVIS_BUILD_NUMBER
  - secure: "dwpMGfJifaVvhPW2y4t15pupKEEON63J+K1N1hMjRWrjNnFWz4fvukmhbW5B5mkUOYmx+ZSQxfLrKyWSYAI9YnjjWEr23KOBs+DwfWBtDIC69kb3c4K1rBSJAUwSdXDJSgU/MkqAeyeGQ4SVA7ftE2yVDvKQ/Yd/r1IRVrQLRsufMaHl4xXiL9yzdBs5Nu0K5xzlxcwIHVaY6OhulXcQ/XS9AcUfbM1KagrWxsRD7rM3F2uWNf9p0LTEcwv22rtFbeDebAZ2Ayb5e2mmTBoVOju5a8NgRndXBDc6veR1QrrUdMs4vCE3qEcMUeIUaERlZhj+iXtTFenPk1YUeCr5wcFfCQD4Lnug93HzSyq/oJkivxmAWmMhD/QV1rmE9mCWGMPo7hdr/USYta5vum+HoEvYH/CzG+ATcjr/0X4AszQq3nzXZP73cKdK1lEY/ZxYtmHqa3/P2pIdJB+wnpPRg2iXlCaDLFa3NmY1RhNMr1zsbLgQM/Db4rqq8sPz59G3SfJaZG1t4ck7YNMR+qA3Tvshfr3uBNjZP8fAlsTKxOqQExg9pG58L37azi5m0ipwcP/xf9N14POvUaKBEr7Jw9VjjqdHq1RbU8qNYzm7VcULur4VgORjGHDOafqdpQlTgHu0RPBS2K9QNn4hG4eTHFD/BbHUOS9oOrx/y9HvSck="
  - secure: "E4LT7HX07YH/TY1Q99j3Uc4e01VWJScM9DDMvOjqXs5HDX2NFkM1T1J/UjFAWGKyz0YxkZpFhtk8wBOH2HNGHwUHUSmxhoWqDpJY9AoSJZ8XHVOYdGbhmeZidhvmER5UuGeYwupZjhOU5meZCTLLsprNkiDpUiozicVJQBWLM+Py4B4Tb5LQZdI8H/l+k2Xto6UuYXbw8koZlSh2GewnkCzY4LfA9q3o4lqvUuqbb/zLLxZ0KSsXfAB7svoouqz9Hc/EzCZCFLCgt4k9UDfnWSnGI/ol0ufzGzS5k9uLe+9GMrpRdrSJCBl6mGKKrEasEvdBJInkoSViMrEZ2ah8TCl9VFrkYob8zbDfr7OSj77HLTfn/W9RKHKMJygnFKDSKTS/tD80av+hydZP8bxTXNKayJmiTo8eEqTR6bC+7eD5vlA9532FAb4C8E0rEZSDpYOyVp60bsG3wjKKeI+I5SQ/UQsbUGuLWsnjtihUs/woW5enVrWzcHuo7BlCVpEP8m0Eo9XvY3RgiNTU6AMreHoYAniyqTYIEqmKBp4rBEokqYmyeIOKIfNQ1yzGyY43SABaDo/Kk+X1X2cP9pygFfDiFnL9WJso3wMvcwv1UlpGGonqdF8VK7pDuP1LPaVkIuudoV8lVUmkqT/qRhK/kCpcOqPllBztqhBxetaHKVU="
  - secure: "ahNgh0oGVDY89WfeSk2hfL4u+pFXy0mXbPGqQRl3xENXo+WatK75/ByYwq8QHS6DNlZEY9YwKcrqD9Nvri7iT8RPsEBTisOT0DOFVx3hzlPhSIzSrOn1dMjCVNtVuj/tZ5GnpwoSuXCq3eiZMNiRFjXTwJaYoAodQszJIgfySVKDe+nQ3Slfn88AqvzZaNhLNbHX6oNU4fq5XOdsneLAl+nKRimYWB6TIxBvr6urOvEp6g+7l48kK/52nqZ+eRlaiV1iy48wm8eWwSslx4i1ogQ41UFu36dQQ/eFecLCLIcxBbu2Qp3DNV1wSK9QR3gNg5c4i9Anpvd8O+DCFu7jocsFGE6vBMLiP/55efy9K7Fwp4dk0fTsHjr5QMXLYFM4TcA+Aoj/xIdMrkC9dkyUWIUEjwIKJGOJVhmKiCxF7IcnAE+VE8eyFgv1GnR/QQ0KojruhkjE7bHorj6YBkM05F/sqUhXTFW1XYlnfYvFDBFmSHYKGa9oAn/URTTxQdFw5XxxBtGyegJP0p07MNTkZEEOb7ZEUPgCI0JveGqbEGDlneKk+tJ2Od/wgDlsCVz7lOECIcxXjZ9d4Vj8WAUZsNh3NrTdUDzLmoI/AEGEXmnKiOqZ4nsVgUi4qSj/P6k28gRhwvdrmda0wdWv85gYxL2qw9TPJY9BlmU0wcuDk0Q="
  - secure: "WLHrOEphrvh7ZKCjRCqeGF3ZkR+GsyL91dh4SMQuC8lmANqgAjS3Kz+UiAlWug7uJQ7QwGpVmIcOVFR3scdIo2B5BnG7yBZjZUfQWpaSQma0E9V6CIHuLbTh86o+2NXv8Bb8MHVGN8D++SxBsTqGjbb0fEWjCkHvMHy/RWLkrlSNhsQnPsYErMbcTu3sVHIFxf1MKjP3c3Bwz0vCMfaLO5dSpComWaBADWzcuD0vPLlFaxjdDZZNlePf39AKCoDuQCMVjSQZrTb5WjCAIqLjpGoQtENLkqa+j8kxjP5XWDAjo2KAtUxPWGAdzYChjIq1uE6RHpdH9xCcusEpoZhVEKtX+pH565Nhv5kY7EmF0Ygwy9qNcbXtvdEbvkb8yXbdV1SFcbXH0QqdEPVj4xv7EDOXlbcZsN/6WRV6M+YqQY/KT4BHBRdG0RqIJvEgy6ay2jnCi55kykqGLcGQg4oGyX1Ftl/sv03DGd1tDMlOSAtJrZvAw61IP0omZ0TmXrhARDsBxyyiU9rl6mKk8XWgCr1MFVk4muMKXmSeTgGJ58xXCFoVw7dji99/lGgDH4LW81JfpwcyauHY7zYgwGZuKVRSc9XZa/fVcbBDXe8sAbMkPKRQ6uALLEVCaYVSF2I3HwR/UGidT+zsgYmcnMDdzjB17I/yHQmTXpvAfqzPJGA="

# directories cached to S3 at the end of the build
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/d6400086732c8d08dd0b
    on_success: change
    on_failure: always
    on_start:   never
